
name: Deploy React Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Generate pre-rendered pages
        run: node scripts/generate-prerender-pages.js
      - name: Build project
        run: npm run build
      - name: Create .nojekyll file  # Prevents GitHub from ignoring files that begin with an underscore
        run: touch ./dist/.nojekyll
      - name: Create blog directories for SEO
        run: |
          mkdir -p ./dist/blog
          mkdir -p ./dist/blog/active-listening-skills
          mkdir -p ./dist/blog/license-to-lead
          mkdir -p ./dist/blog/lead-vs-inspire
          mkdir -p ./dist/blog/everyone-leader
      - name: Create blog HTML files for SEO
        run: |
          cp ./dist/index.html ./dist/blog/index.html
          cp ./dist/index.html ./dist/blog/active-listening-skills/index.html
          cp ./dist/index.html ./dist/blog/license-to-lead/index.html
          cp ./dist/index.html ./dist/blog/lead-vs-inspire/index.html
          cp ./dist/index.html ./dist/blog/everyone-leader/index.html
      - name: Copy pre-rendered pages to dist
        run: |
          cp -r ./public/books-pr ./dist/
          cp -r ./public/blog-pr ./dist/
      - name: Make sure blog images are copied
        run: |
          mkdir -p ./dist/img/blog
          cp -r ./public/img/blog/* ./dist/img/blog/ || true
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
